//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GettingStartedClient.PalindromeRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Microsoft.ServiceModel.Samples", ConfigurationName="PalindromeRef.IPalindrome")]
    public interface IPalindrome {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IPalindrome/IsPalindrome", ReplyAction="http://Microsoft.ServiceModel.Samples/IPalindrome/IsPalindromeResponse")]
        bool IsPalindrome(string word);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Microsoft.ServiceModel.Samples/IPalindrome/IsPalindrome", ReplyAction="http://Microsoft.ServiceModel.Samples/IPalindrome/IsPalindromeResponse")]
        System.Threading.Tasks.Task<bool> IsPalindromeAsync(string word);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPalindromeChannel : GettingStartedClient.PalindromeRef.IPalindrome, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PalindromeClient : System.ServiceModel.ClientBase<GettingStartedClient.PalindromeRef.IPalindrome>, GettingStartedClient.PalindromeRef.IPalindrome {
        
        public PalindromeClient() {
        }
        
        public PalindromeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PalindromeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PalindromeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PalindromeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsPalindrome(string word) {
            return base.Channel.IsPalindrome(word);
        }
        
        public System.Threading.Tasks.Task<bool> IsPalindromeAsync(string word) {
            return base.Channel.IsPalindromeAsync(word);
        }
    }
}
